Repository graz-sh/graz, pull requests merged in 2022-11, with the labels that each got.

#51 CosmWasm smart contract hooks
  packages/graz/src/actions/methods.ts
  packages/graz/src/hooks/methods.ts
Labels: enhancement

#53 Fix linting error in graz template
  templates/default/src/pages/send-token.tsx
Labels: bug

#56 fix(docs): resolve typo
  docs/docs/hooks/useAccount.md
Labels: enhancement, good first issue
